version: '3'

services:
  node:
    image: node:16.14
    container_name: ta_na_epoca
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - database
    ports:
      - 3001:3001
      - 9229:9229
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: database
      PORT: 3001
  
  database:
    image: mysql:8.0.29
    container_name: ta_na_epoca_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taNaEpoca
    ports:
      - 3306:3306
    volumes:
      - ./:/docker-entrypoint-initdb.d