INSERT INTO "Food" (name, color, type) VALUES ('Abacate Avocado', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abacate Breda', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abacate Fortuna', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abacate Geada', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abacate Margarida', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abacate Quintal', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abacaxi Havai', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abacaxi Pérola', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abiu', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Acerola', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Ameixa Nacional', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Amora', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Atemoia', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Avelã', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Banana Maçã', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Banana Nanica', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Banana Ouro', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Banana Prata MG', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Banana Prata SP', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Banana Terra', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cacau', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Caju', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Caqui Chocolate Kyoto', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Caqui Fuyu', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Caqui Giombo', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Caqui Rama Forte', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Carambola', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Castanha Nacional', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Coco Verde', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cupuaçu', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Embu', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Figo', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Framboesa', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Goiaba', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Grapefruit', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Graviola', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Jabuticaba', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Jaca', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Jambo', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Jatobá', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Jenipapo', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Kiwi Nacional', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Laranja Baia', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Laranja Lima', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Laranja Pera', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Laranja Seleta', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Laranja Valência', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Lichia', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Lima Pérsia', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Limão Galego', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Limão Rosa', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Limão Siciliano', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Limão Taiti', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Longan', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Maçã Eva', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Maçã Fuji', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Maçã Gala', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Maçã Golden Del', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Mamão Formosa', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Mamão Havaí', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Bourbon', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Coquinho', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Espada', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Haden', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Keity', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Lolita', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Palmer', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Rosa', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Shelly', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manga Tommy', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Mangostim', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Maracujá Azedo', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Maracujá Doce', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Melancia Baby', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Melancia', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Melão Amarelo', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Melão Gália', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Melão Net Melon', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Melão Orange', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Melão Pele de Sapo', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Mexerica Rio', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Mirtilo', 'blue', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Morango Comum', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Nectarina Nacional', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Nêspera', 'yellow', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Nozes Pecan', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pera Nacional', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Aurora', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Chimarrita', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Dourado', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Eragil', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Fascinio', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Kampai', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Nacional', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Rubimel', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Tropic Beauty', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pêssego Xiripa', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Physalis', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pinha', 'green', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pitaia', 'pink', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pitanga', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Quincam', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Rambutã', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Romã', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Sapoti', 'brown', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Seriguela', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tamarillo', 'red', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tangerina Cravo', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tangerina Decopom', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tangerina Murcote', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tangerina Ole', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tangerina Poncã', 'orange', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Arra 15', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Benitaka', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Brasil', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Centenial', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Crinsom', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Isabel', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Isis', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Italia', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Melodia', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Niagara', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Red Globe', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Rubi', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Thompson', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Uva Vitoria', 'purple', 'FRUIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abóbora D´Agua', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abóbora Japonesa', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abóbora Moranga', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abóbora Paulista', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abóbora Seca', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abobrinha Brasileira', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Abobrinha Italiana', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alcachofra', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Batata Doce Amarela', 'yellow', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Batata Doce Branca', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Batata Doce Rosada', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Batata Doce Roxa', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Batata Yakon', 'yellow', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Berinjela Comum', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Berinjela Japonesa', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Beterraba', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cará', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cenoura', 'orange', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Chuchu', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Ervilha Torta', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Feijão de Corda', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Gengibre', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Inhame', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Jiló', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Lakio', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Lenkon', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Mandioca', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Mandioquinha', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Maxixe', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Miyoga', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Nigagori', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pepino Caipira', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pepino Comum', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pepino Japonês', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pimenta Cambuci', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pimenta Dedo de Moça', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pimenta Malagueta/Malaguetão', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pimenta Verde', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pimenta Verde Americana', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pimentão Amarelo', 'yellow', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pimentão Verde', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pimentão Vermelho', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Quiabo', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Taquenoco', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tomate Caqui', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tomate Carmem', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tomate Cereja', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tomate Debora', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tomate Holandês', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tomate Italiano - Pizzadoro', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tomate Rasteiro', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tomate Sweet Grape', 'red', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Ume', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Vagem Macarrão', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Vagem Manteiga', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Vagem Metro', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Acelga Chinesa', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Acelga', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Agrião', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Agrião Hidropônico', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alecrim', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alface Americana', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alface Crespa', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alface Crespa Hidropônica', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alface Lisa', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alface Lisa Hidropônica', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alface Mimosa', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alface Mimosa Hidropônica', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alface Romana', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alface Romana Hidropônica', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alfavaca', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alho Porro', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Almeirão', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Almeirão Hidropônico', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Almeirão Pão de Açucar', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Aspargo', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Beterraba com Folhas', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Brócolos Ninja', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Brócolos Ramoso', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Broto de Alfafa', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Capim Cidreira', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Catalonha', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cebolete', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cebolinha', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cenoura com Folhas', 'orange', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Chicória', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Coentro', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cogumelo Eryngui', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cogumelo Hiratake', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cogumelo Paris', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cogumelo Porto Belo', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cogumelo Shimeji', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cogumelo Shitake', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Couve Manteiga', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Couve de Bruxelas', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Couve-Flor', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Endívia', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Endro', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Erva Doce', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Escarola', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Escarola Hidropônica', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Espinafre', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Espinafre Hidropônico', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Estragão', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Gengibre com Folhas', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Gobô', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Hana Nira', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Hortelã', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Louro', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manjericão', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Manjerona', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Milho Verde', 'yellow', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Mostarda', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Mostarda Hidropônica', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Moyashi', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Nabo', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Orégano', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Palmito Pupunha', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Rabanete', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Radicchio', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Repolho Verde Liso', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Repolho Roxo', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Rúcula', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Rúcula Hidropônica', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Salsa', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Salsão Branco/Verde', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Sálvia', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Tomilho', 'green', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Alho Nacional', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Amendoim com Casca', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Amendoim sem Casca', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Batata Asterix', 'yellow', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Batata Lavada', 'yellow', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cebola Nacional', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cebola Pérola', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Cebola Roxa', 'purple', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Coco Seco', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Food" (name, color, type) VALUES ('Pinhão', 'brown', 'VEGETABLE') ON CONFLICT (name) DO NOTHING;
