UPDATE "Food" SET name_formatted = 'abacate avocado' WHERE name = 'Abacate Avocado';
UPDATE "Food" SET name_formatted = 'abacate breda' WHERE name = 'Abacate Breda';
UPDATE "Food" SET name_formatted = 'abacate fortuna' WHERE name = 'Abacate Fortuna';
UPDATE "Food" SET name_formatted = 'abacate geada' WHERE name = 'Abacate Geada';
UPDATE "Food" SET name_formatted = 'abacate margarida' WHERE name = 'Abacate Margarida';
UPDATE "Food" SET name_formatted = 'abacate quintal' WHERE name = 'Abacate Quintal';
UPDATE "Food" SET name_formatted = 'abacaxi havai' WHERE name = 'Abacaxi Havai';
UPDATE "Food" SET name_formatted = 'abacaxi perola' WHERE name = 'Abacaxi Pérola';
UPDATE "Food" SET name_formatted = 'abiu' WHERE name = 'Abiu';
UPDATE "Food" SET name_formatted = 'abobora d''agua' WHERE name = 'Abóbora D´Agua';
UPDATE "Food" SET name_formatted = 'abobora japonesa' WHERE name = 'Abóbora Japonesa';
UPDATE "Food" SET name_formatted = 'abobora moranga' WHERE name = 'Abóbora Moranga';
UPDATE "Food" SET name_formatted = 'abobora paulista' WHERE name = 'Abóbora Paulista';
UPDATE "Food" SET name_formatted = 'abobora seca' WHERE name = 'Abóbora Seca';
UPDATE "Food" SET name_formatted = 'abobrinha brasileira' WHERE name = 'Abobrinha Brasileira';
UPDATE "Food" SET name_formatted = 'abobrinha italiana' WHERE name = 'Abobrinha Italiana';
UPDATE "Food" SET name_formatted = 'acelga' WHERE name = 'Acelga';
UPDATE "Food" SET name_formatted = 'acelga chinesa' WHERE name = 'Acelga Chinesa';
UPDATE "Food" SET name_formatted = 'acerola' WHERE name = 'Acerola';
UPDATE "Food" SET name_formatted = 'agriao' WHERE name = 'Agrião';
UPDATE "Food" SET name_formatted = 'agriao hidroponico' WHERE name = 'Agrião Hidropônico';
UPDATE "Food" SET name_formatted = 'alcachofra' WHERE name = 'Alcachofra';
UPDATE "Food" SET name_formatted = 'alecrim' WHERE name = 'Alecrim';
UPDATE "Food" SET name_formatted = 'alface americana' WHERE name = 'Alface Americana';
UPDATE "Food" SET name_formatted = 'alface crespa' WHERE name = 'Alface Crespa';
UPDATE "Food" SET name_formatted = 'alface crespa hidroponica' WHERE name = 'Alface Crespa Hidropônica';
UPDATE "Food" SET name_formatted = 'alface lisa' WHERE name = 'Alface Lisa';
UPDATE "Food" SET name_formatted = 'alface lisa hidroponica' WHERE name = 'Alface Lisa Hidropônica';
UPDATE "Food" SET name_formatted = 'alface mimosa' WHERE name = 'Alface Mimosa';
UPDATE "Food" SET name_formatted = 'alface mimosa hidroponica' WHERE name = 'Alface Mimosa Hidropônica';
UPDATE "Food" SET name_formatted = 'alface romana' WHERE name = 'Alface Romana';
UPDATE "Food" SET name_formatted = 'alface romana hidroponica' WHERE name = 'Alface Romana Hidropônica';
UPDATE "Food" SET name_formatted = 'alfavaca' WHERE name = 'Alfavaca';
UPDATE "Food" SET name_formatted = 'alho nacional' WHERE name = 'Alho Nacional';
UPDATE "Food" SET name_formatted = 'alho porro' WHERE name = 'Alho Porro';
UPDATE "Food" SET name_formatted = 'almeirao' WHERE name = 'Almeirão';
UPDATE "Food" SET name_formatted = 'almeirao hidroponico' WHERE name = 'Almeirão Hidropônico';
UPDATE "Food" SET name_formatted = 'almeirao pao de acucar' WHERE name = 'Almeirão Pão de Açucar';
UPDATE "Food" SET name_formatted = 'ameixa nacional' WHERE name = 'Ameixa Nacional';
UPDATE "Food" SET name_formatted = 'amendoim com casca' WHERE name = 'Amendoim com Casca';
UPDATE "Food" SET name_formatted = 'amendoim sem casca' WHERE name = 'Amendoim sem Casca';
UPDATE "Food" SET name_formatted = 'amora' WHERE name = 'Amora';
UPDATE "Food" SET name_formatted = 'aspargo' WHERE name = 'Aspargo';
UPDATE "Food" SET name_formatted = 'atemoia' WHERE name = 'Atemoia';
UPDATE "Food" SET name_formatted = 'avela' WHERE name = 'Avelã';
UPDATE "Food" SET name_formatted = 'banana maca' WHERE name = 'Banana Maçã';
UPDATE "Food" SET name_formatted = 'banana nanica' WHERE name = 'Banana Nanica';
UPDATE "Food" SET name_formatted = 'banana ouro' WHERE name = 'Banana Ouro';
UPDATE "Food" SET name_formatted = 'banana prata mg' WHERE name = 'Banana Prata MG';
UPDATE "Food" SET name_formatted = 'banana prata sp' WHERE name = 'Banana Prata SP';
UPDATE "Food" SET name_formatted = 'banana terra' WHERE name = 'Banana Terra';
UPDATE "Food" SET name_formatted = 'batata asterix' WHERE name = 'Batata Asterix';
UPDATE "Food" SET name_formatted = 'batata doce amarela' WHERE name = 'Batata Doce Amarela';
UPDATE "Food" SET name_formatted = 'batata doce branca' WHERE name = 'Batata Doce Branca';
UPDATE "Food" SET name_formatted = 'batata doce rosada' WHERE name = 'Batata Doce Rosada';
UPDATE "Food" SET name_formatted = 'batata doce roxa' WHERE name = 'Batata Doce Roxa';
UPDATE "Food" SET name_formatted = 'batata lavada' WHERE name = 'Batata Lavada';
UPDATE "Food" SET name_formatted = 'batata yakon' WHERE name = 'Batata Yakon';
UPDATE "Food" SET name_formatted = 'berinjela comum' WHERE name = 'Berinjela Comum';
UPDATE "Food" SET name_formatted = 'berinjela japonesa' WHERE name = 'Berinjela Japonesa';
UPDATE "Food" SET name_formatted = 'beterraba' WHERE name = 'Beterraba';
UPDATE "Food" SET name_formatted = 'beterraba com folhas' WHERE name = 'Beterraba com Folhas';
UPDATE "Food" SET name_formatted = 'brocolis ninja' WHERE name = 'Brócolis Ninja';
UPDATE "Food" SET name_formatted = 'brocolis ramoso' WHERE name = 'Brócolis Ramoso';
UPDATE "Food" SET name_formatted = 'broto de alfafa' WHERE name = 'Broto de Alfafa';
UPDATE "Food" SET name_formatted = 'cacau' WHERE name = 'Cacau';
UPDATE "Food" SET name_formatted = 'caju' WHERE name = 'Caju';
UPDATE "Food" SET name_formatted = 'capim cidreira' WHERE name = 'Capim Cidreira';
UPDATE "Food" SET name_formatted = 'caqui chocolate kyoto' WHERE name = 'Caqui Chocolate Kyoto';
UPDATE "Food" SET name_formatted = 'caqui fuyu' WHERE name = 'Caqui Fuyu';
UPDATE "Food" SET name_formatted = 'caqui giombo' WHERE name = 'Caqui Giombo';
UPDATE "Food" SET name_formatted = 'caqui rama forte' WHERE name = 'Caqui Rama Forte';
UPDATE "Food" SET name_formatted = 'cara' WHERE name = 'Cará';
UPDATE "Food" SET name_formatted = 'carambola' WHERE name = 'Carambola';
UPDATE "Food" SET name_formatted = 'castanha nacional' WHERE name = 'Castanha Nacional';
UPDATE "Food" SET name_formatted = 'catalonha' WHERE name = 'Catalonha';
UPDATE "Food" SET name_formatted = 'cebola nacional' WHERE name = 'Cebola Nacional';
UPDATE "Food" SET name_formatted = 'cebola perola' WHERE name = 'Cebola Pérola';
UPDATE "Food" SET name_formatted = 'cebola roxa' WHERE name = 'Cebola Roxa';
UPDATE "Food" SET name_formatted = 'cebolete' WHERE name = 'Cebolete';
UPDATE "Food" SET name_formatted = 'cebolinha' WHERE name = 'Cebolinha';
UPDATE "Food" SET name_formatted = 'cenoura' WHERE name = 'Cenoura';
UPDATE "Food" SET name_formatted = 'cenoura com folhas' WHERE name = 'Cenoura com Folhas';
UPDATE "Food" SET name_formatted = 'chicoria' WHERE name = 'Chicória';
UPDATE "Food" SET name_formatted = 'chuchu' WHERE name = 'Chuchu';
UPDATE "Food" SET name_formatted = 'coco seco' WHERE name = 'Coco Seco';
UPDATE "Food" SET name_formatted = 'coco verde' WHERE name = 'Coco Verde';
UPDATE "Food" SET name_formatted = 'coentro' WHERE name = 'Coentro';
UPDATE "Food" SET name_formatted = 'cogumelo eryngui' WHERE name = 'Cogumelo Eryngui';
UPDATE "Food" SET name_formatted = 'cogumelo hiratake' WHERE name = 'Cogumelo Hiratake';
UPDATE "Food" SET name_formatted = 'cogumelo paris' WHERE name = 'Cogumelo Paris';
UPDATE "Food" SET name_formatted = 'cogumelo porto belo' WHERE name = 'Cogumelo Porto Belo';
UPDATE "Food" SET name_formatted = 'cogumelo shimeji' WHERE name = 'Cogumelo Shimeji';
UPDATE "Food" SET name_formatted = 'cogumelo shitake' WHERE name = 'Cogumelo Shitake';
UPDATE "Food" SET name_formatted = 'couve de bruxelas' WHERE name = 'Couve de Bruxelas';
UPDATE "Food" SET name_formatted = 'couve manteiga' WHERE name = 'Couve Manteiga';
UPDATE "Food" SET name_formatted = 'couve-flor' WHERE name = 'Couve-Flor';
UPDATE "Food" SET name_formatted = 'cupuacu' WHERE name = 'Cupuaçu';
UPDATE "Food" SET name_formatted = 'embu' WHERE name = 'Embu';
UPDATE "Food" SET name_formatted = 'endivia' WHERE name = 'Endívia';
UPDATE "Food" SET name_formatted = 'endro' WHERE name = 'Endro';
UPDATE "Food" SET name_formatted = 'erva doce' WHERE name = 'Erva Doce';
UPDATE "Food" SET name_formatted = 'ervilha torta' WHERE name = 'Ervilha Torta';
UPDATE "Food" SET name_formatted = 'escarola' WHERE name = 'Escarola';
UPDATE "Food" SET name_formatted = 'escarola hidroponica' WHERE name = 'Escarola Hidropônica';
UPDATE "Food" SET name_formatted = 'espinafre' WHERE name = 'Espinafre';
UPDATE "Food" SET name_formatted = 'espinafre hidroponico' WHERE name = 'Espinafre Hidropônico';
UPDATE "Food" SET name_formatted = 'estragao' WHERE name = 'Estragão';
UPDATE "Food" SET name_formatted = 'feijao de corda' WHERE name = 'Feijão de Corda';
UPDATE "Food" SET name_formatted = 'figo' WHERE name = 'Figo';
UPDATE "Food" SET name_formatted = 'framboesa' WHERE name = 'Framboesa';
UPDATE "Food" SET name_formatted = 'gengibre' WHERE name = 'Gengibre';
UPDATE "Food" SET name_formatted = 'gengibre com folhas' WHERE name = 'Gengibre com Folhas';
UPDATE "Food" SET name_formatted = 'gobo' WHERE name = 'Gobô';
UPDATE "Food" SET name_formatted = 'goiaba' WHERE name = 'Goiaba';
UPDATE "Food" SET name_formatted = 'grapefruit' WHERE name = 'Grapefruit';
UPDATE "Food" SET name_formatted = 'graviola' WHERE name = 'Graviola';
UPDATE "Food" SET name_formatted = 'hana nira' WHERE name = 'Hana Nira';
UPDATE "Food" SET name_formatted = 'hortela' WHERE name = 'Hortelã';
UPDATE "Food" SET name_formatted = 'inhame' WHERE name = 'Inhame';
UPDATE "Food" SET name_formatted = 'jabuticaba' WHERE name = 'Jabuticaba';
UPDATE "Food" SET name_formatted = 'jaca' WHERE name = 'Jaca';
UPDATE "Food" SET name_formatted = 'jambo' WHERE name = 'Jambo';
UPDATE "Food" SET name_formatted = 'jatoba' WHERE name = 'Jatobá';
UPDATE "Food" SET name_formatted = 'jenipapo' WHERE name = 'Jenipapo';
UPDATE "Food" SET name_formatted = 'jilo' WHERE name = 'Jiló';
UPDATE "Food" SET name_formatted = 'kiwi nacional' WHERE name = 'Kiwi Nacional';
UPDATE "Food" SET name_formatted = 'lakio' WHERE name = 'Lakio';
UPDATE "Food" SET name_formatted = 'laranja baia' WHERE name = 'Laranja Baia';
UPDATE "Food" SET name_formatted = 'laranja lima' WHERE name = 'Laranja Lima';
UPDATE "Food" SET name_formatted = 'laranja pera' WHERE name = 'Laranja Pera';
UPDATE "Food" SET name_formatted = 'laranja seleta' WHERE name = 'Laranja Seleta';
UPDATE "Food" SET name_formatted = 'laranja valencia' WHERE name = 'Laranja Valência';
UPDATE "Food" SET name_formatted = 'lenkon' WHERE name = 'Lenkon';
UPDATE "Food" SET name_formatted = 'lichia' WHERE name = 'Lichia';
UPDATE "Food" SET name_formatted = 'lima persia' WHERE name = 'Lima Pérsia';
UPDATE "Food" SET name_formatted = 'limao galego' WHERE name = 'Limão Galego';
UPDATE "Food" SET name_formatted = 'limao rosa' WHERE name = 'Limão Rosa';
UPDATE "Food" SET name_formatted = 'limao siciliano' WHERE name = 'Limão Siciliano';
UPDATE "Food" SET name_formatted = 'limao taiti' WHERE name = 'Limão Taiti';
UPDATE "Food" SET name_formatted = 'longan' WHERE name = 'Longan';
UPDATE "Food" SET name_formatted = 'louro' WHERE name = 'Louro';
UPDATE "Food" SET name_formatted = 'maca eva' WHERE name = 'Maçã Eva';
UPDATE "Food" SET name_formatted = 'maca fuji' WHERE name = 'Maçã Fuji';
UPDATE "Food" SET name_formatted = 'maca gala' WHERE name = 'Maçã Gala';
UPDATE "Food" SET name_formatted = 'maca golden del' WHERE name = 'Maçã Golden Del';
UPDATE "Food" SET name_formatted = 'mamao formosa' WHERE name = 'Mamão Formosa';
UPDATE "Food" SET name_formatted = 'mamao havai' WHERE name = 'Mamão Havaí';
UPDATE "Food" SET name_formatted = 'mandioca' WHERE name = 'Mandioca';
UPDATE "Food" SET name_formatted = 'mandioquinha' WHERE name = 'Mandioquinha';
UPDATE "Food" SET name_formatted = 'manga bourbon' WHERE name = 'Manga Bourbon';
UPDATE "Food" SET name_formatted = 'manga coquinho' WHERE name = 'Manga Coquinho';
UPDATE "Food" SET name_formatted = 'manga espada' WHERE name = 'Manga Espada';
UPDATE "Food" SET name_formatted = 'manga haden' WHERE name = 'Manga Haden';
UPDATE "Food" SET name_formatted = 'manga keity' WHERE name = 'Manga Keity';
UPDATE "Food" SET name_formatted = 'manga lolita' WHERE name = 'Manga Lolita';
UPDATE "Food" SET name_formatted = 'manga palmer' WHERE name = 'Manga Palmer';
UPDATE "Food" SET name_formatted = 'manga rosa' WHERE name = 'Manga Rosa';
UPDATE "Food" SET name_formatted = 'manga shelly' WHERE name = 'Manga Shelly';
UPDATE "Food" SET name_formatted = 'manga tommy' WHERE name = 'Manga Tommy';
UPDATE "Food" SET name_formatted = 'mangostim' WHERE name = 'Mangostim';
UPDATE "Food" SET name_formatted = 'manjericao' WHERE name = 'Manjericão';
UPDATE "Food" SET name_formatted = 'manjerona' WHERE name = 'Manjerona';
UPDATE "Food" SET name_formatted = 'maracuja azedo' WHERE name = 'Maracujá Azedo';
UPDATE "Food" SET name_formatted = 'maracuja doce' WHERE name = 'Maracujá Doce';
UPDATE "Food" SET name_formatted = 'maxixe' WHERE name = 'Maxixe';
UPDATE "Food" SET name_formatted = 'melancia' WHERE name = 'Melancia';
UPDATE "Food" SET name_formatted = 'melancia baby' WHERE name = 'Melancia Baby';
UPDATE "Food" SET name_formatted = 'melao amarelo' WHERE name = 'Melão Amarelo';
UPDATE "Food" SET name_formatted = 'melao galia' WHERE name = 'Melão Gália';
UPDATE "Food" SET name_formatted = 'melao net melon' WHERE name = 'Melão Net Melon';
UPDATE "Food" SET name_formatted = 'melao orange' WHERE name = 'Melão Orange';
UPDATE "Food" SET name_formatted = 'melao pele de sapo' WHERE name = 'Melão Pele de Sapo';
UPDATE "Food" SET name_formatted = 'mexerica rio' WHERE name = 'Mexerica Rio';
UPDATE "Food" SET name_formatted = 'milho verde' WHERE name = 'Milho Verde';
UPDATE "Food" SET name_formatted = 'mirtilo' WHERE name = 'Mirtilo';
UPDATE "Food" SET name_formatted = 'miyoga' WHERE name = 'Miyoga';
UPDATE "Food" SET name_formatted = 'morango comum' WHERE name = 'Morango Comum';
UPDATE "Food" SET name_formatted = 'mostarda' WHERE name = 'Mostarda';
UPDATE "Food" SET name_formatted = 'mostarda hidroponica' WHERE name = 'Mostarda Hidropônica';
UPDATE "Food" SET name_formatted = 'moyashi' WHERE name = 'Moyashi';
UPDATE "Food" SET name_formatted = 'nabo' WHERE name = 'Nabo';
UPDATE "Food" SET name_formatted = 'nectarina nacional' WHERE name = 'Nectarina Nacional';
UPDATE "Food" SET name_formatted = 'nespera' WHERE name = 'Nêspera';
UPDATE "Food" SET name_formatted = 'nigagori' WHERE name = 'Nigagori';
UPDATE "Food" SET name_formatted = 'nozes pecan' WHERE name = 'Nozes Pecan';
UPDATE "Food" SET name_formatted = 'oregano' WHERE name = 'Orégano';
UPDATE "Food" SET name_formatted = 'palmito pupunha' WHERE name = 'Palmito Pupunha';
UPDATE "Food" SET name_formatted = 'pepino caipira' WHERE name = 'Pepino Caipira';
UPDATE "Food" SET name_formatted = 'pepino comum' WHERE name = 'Pepino Comum';
UPDATE "Food" SET name_formatted = 'pepino japones' WHERE name = 'Pepino Japonês';
UPDATE "Food" SET name_formatted = 'pera nacional' WHERE name = 'Pera Nacional';
UPDATE "Food" SET name_formatted = 'pessego aurora' WHERE name = 'Pêssego Aurora';
UPDATE "Food" SET name_formatted = 'pessego chimarrita' WHERE name = 'Pêssego Chimarrita';
UPDATE "Food" SET name_formatted = 'pessego dourado' WHERE name = 'Pêssego Dourado';
UPDATE "Food" SET name_formatted = 'pessego eragil' WHERE name = 'Pêssego Eragil';
UPDATE "Food" SET name_formatted = 'pessego fascinio' WHERE name = 'Pêssego Fascinio';
UPDATE "Food" SET name_formatted = 'pessego kampai' WHERE name = 'Pêssego Kampai';
UPDATE "Food" SET name_formatted = 'pessego nacional' WHERE name = 'Pêssego Nacional';
UPDATE "Food" SET name_formatted = 'pessego rubimel' WHERE name = 'Pêssego Rubimel';
UPDATE "Food" SET name_formatted = 'pessego tropic beauty' WHERE name = 'Pêssego Tropic Beauty';
UPDATE "Food" SET name_formatted = 'pessego xiripa' WHERE name = 'Pêssego Xiripa';
UPDATE "Food" SET name_formatted = 'physalis' WHERE name = 'Physalis';
UPDATE "Food" SET name_formatted = 'pimenta cambuci' WHERE name = 'Pimenta Cambuci';
UPDATE "Food" SET name_formatted = 'pimenta dedo de moca' WHERE name = 'Pimenta Dedo de Moça';
UPDATE "Food" SET name_formatted = 'pimenta malagueta/malaguetao' WHERE name = 'Pimenta Malagueta/Malaguetão';
UPDATE "Food" SET name_formatted = 'pimenta verde' WHERE name = 'Pimenta Verde';
UPDATE "Food" SET name_formatted = 'pimenta verde americana' WHERE name = 'Pimenta Verde Americana';
UPDATE "Food" SET name_formatted = 'pimentao amarelo' WHERE name = 'Pimentão Amarelo';
UPDATE "Food" SET name_formatted = 'pimentao verde' WHERE name = 'Pimentão Verde';
UPDATE "Food" SET name_formatted = 'pimentao vermelho' WHERE name = 'Pimentão Vermelho';
UPDATE "Food" SET name_formatted = 'pinha' WHERE name = 'Pinha';
UPDATE "Food" SET name_formatted = 'pinhao' WHERE name = 'Pinhão';
UPDATE "Food" SET name_formatted = 'pitaia' WHERE name = 'Pitaia';
UPDATE "Food" SET name_formatted = 'pitanga' WHERE name = 'Pitanga';
UPDATE "Food" SET name_formatted = 'quiabo' WHERE name = 'Quiabo';
UPDATE "Food" SET name_formatted = 'quincam' WHERE name = 'Quincam';
UPDATE "Food" SET name_formatted = 'rabanete' WHERE name = 'Rabanete';
UPDATE "Food" SET name_formatted = 'radicchio' WHERE name = 'Radicchio';
UPDATE "Food" SET name_formatted = 'rambuta' WHERE name = 'Rambutã';
UPDATE "Food" SET name_formatted = 'repolho roxo' WHERE name = 'Repolho Roxo';
UPDATE "Food" SET name_formatted = 'repolho verde liso' WHERE name = 'Repolho Verde Liso';
UPDATE "Food" SET name_formatted = 'roma' WHERE name = 'Romã';
UPDATE "Food" SET name_formatted = 'rucula' WHERE name = 'Rúcula';
UPDATE "Food" SET name_formatted = 'rucula hidroponica' WHERE name = 'Rúcula Hidropônica';
UPDATE "Food" SET name_formatted = 'salsa' WHERE name = 'Salsa';
UPDATE "Food" SET name_formatted = 'salsao branco/verde' WHERE name = 'Salsão Branco/Verde';
UPDATE "Food" SET name_formatted = 'salvia' WHERE name = 'Sálvia';
UPDATE "Food" SET name_formatted = 'sapoti' WHERE name = 'Sapoti';
UPDATE "Food" SET name_formatted = 'seriguela' WHERE name = 'Seriguela';
UPDATE "Food" SET name_formatted = 'tamarillo' WHERE name = 'Tamarillo';
UPDATE "Food" SET name_formatted = 'tangerina cravo' WHERE name = 'Tangerina Cravo';
UPDATE "Food" SET name_formatted = 'tangerina decopom' WHERE name = 'Tangerina Decopom';
UPDATE "Food" SET name_formatted = 'tangerina murcote' WHERE name = 'Tangerina Murcote';
UPDATE "Food" SET name_formatted = 'tangerina ole' WHERE name = 'Tangerina Ole';
UPDATE "Food" SET name_formatted = 'tangerina ponca' WHERE name = 'Tangerina Poncã';
UPDATE "Food" SET name_formatted = 'taquenoco' WHERE name = 'Taquenoco';
UPDATE "Food" SET name_formatted = 'tomate caqui' WHERE name = 'Tomate Caqui';
UPDATE "Food" SET name_formatted = 'tomate carmem' WHERE name = 'Tomate Carmem';
UPDATE "Food" SET name_formatted = 'tomate cereja' WHERE name = 'Tomate Cereja';
UPDATE "Food" SET name_formatted = 'tomate debora' WHERE name = 'Tomate Debora';
UPDATE "Food" SET name_formatted = 'tomate holandes' WHERE name = 'Tomate Holandês';
UPDATE "Food" SET name_formatted = 'tomate italiano (pizzadoro)' WHERE name = 'Tomate Italiano (Pizzadoro)';
UPDATE "Food" SET name_formatted = 'tomate rasteiro' WHERE name = 'Tomate Rasteiro';
UPDATE "Food" SET name_formatted = 'tomate sweet grape' WHERE name = 'Tomate Sweet Grape';
UPDATE "Food" SET name_formatted = 'tomilho' WHERE name = 'Tomilho';
UPDATE "Food" SET name_formatted = 'ume' WHERE name = 'Ume';
UPDATE "Food" SET name_formatted = 'uva arra 15' WHERE name = 'Uva Arra 15';
UPDATE "Food" SET name_formatted = 'uva benitaka' WHERE name = 'Uva Benitaka';
UPDATE "Food" SET name_formatted = 'uva brasil' WHERE name = 'Uva Brasil';
UPDATE "Food" SET name_formatted = 'uva centenial' WHERE name = 'Uva Centenial';
UPDATE "Food" SET name_formatted = 'uva crinsom' WHERE name = 'Uva Crinsom';
UPDATE "Food" SET name_formatted = 'uva isabel' WHERE name = 'Uva Isabel';
UPDATE "Food" SET name_formatted = 'uva isis' WHERE name = 'Uva Isis';
UPDATE "Food" SET name_formatted = 'uva italia' WHERE name = 'Uva Italia';
UPDATE "Food" SET name_formatted = 'uva melodia' WHERE name = 'Uva Melodia';
UPDATE "Food" SET name_formatted = 'uva niagara' WHERE name = 'Uva Niagara';
UPDATE "Food" SET name_formatted = 'uva red globe' WHERE name = 'Uva Red Globe';
UPDATE "Food" SET name_formatted = 'uva rubi' WHERE name = 'Uva Rubi';
UPDATE "Food" SET name_formatted = 'uva thompson' WHERE name = 'Uva Thompson';
UPDATE "Food" SET name_formatted = 'uva vitoria' WHERE name = 'Uva Vitoria';
UPDATE "Food" SET name_formatted = 'vagem macarrao' WHERE name = 'Vagem Macarrão';
UPDATE "Food" SET name_formatted = 'vagem manteiga' WHERE name = 'Vagem Manteiga';
UPDATE "Food" SET name_formatted = 'vagem metro' WHERE name = 'Vagem Metro';
